version: '3'

services:
  web:
    build:
      context: .
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      # dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=unix$DISPLAY
    command: python manage.py runserver 0.0.0.0:8000
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
# runtime: nvidia
